sudo: required

services:
  - docker

language: node_js

node_js:
  - "8.6.0"

env:
    global:
      - CC_TEST_REPORTER_ID=f9a7cc51d41f847d9b5c91f469606222755355ec9ea001c6bd7a16d20f45941f

notifications:
    slack: gppmds8-github:sJE6QlBfPGMkfUf48wuTsKa7

before_install:
  - docker build -t alaxalves/front -f Dockerfile.test .

before_script:
  - npm install coveralls

script:
  - docker run -v /home/travis/build/fga-gpp-mds/Falko-2017.2-FrontEnd:/Falko-2017.2-FrontEnd alaxalves/front /bin/sh -c "npm run unit"

after_script:
  - ./node_modules/coveralls/bin/coveralls.js < ./test/unit/coverage/lcov.info
