sudo: required

language: node_js
 
node_js:
  - 8.6.0

env:
  global:
    - CC_TEST_REPORTER_ID=f9a7cc51d41f847d9b5c91f469606222755355ec9ea001c6bd7a16d20f45941f
  matrix:
    - TASK="yarn unit"
    - TASK="npx cypress run"

script:
  - $TASK
