version: '2'
services:
  
  falko-front:
    container_name: falko-front
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/Falko-2017.2-FrontEnd
    external_links:
      - falko20172backend_default
    ports:
      - 80:8080
    networks:
      - default
      - falko20172backend_default

networks:
  falko20172backend_default: 
    external: true
     
    
